### ISSUE TITLE
Test completion

### ISSUE THREAD

**Issue by hkage** [rheinwerk-verlag/postgresql-anonymizer#3]
Due to the urgency most parts of the project are untestet. Therefore a lot of unittest should be added, mostly for the utils.py package.

**Comment by nurikk** [comment]
- Knock knock 
- Who’s it?
- Technical debt
😁

**Comment by hkage** [comment]
Yeah, I know :smile: Hopefully I can invest some more time into this project (especially when we use it more frequently for our main development dumps). But as I uploaded the project it to Github I felt like it could help other developers out there, even in this early stage of the development.

**Comment by hkage** [comment]
I closed the issue as @nurikk already added so many tests that the code coverage is currently almost at 100%.
