### ISSUE TITLE
parmap no longer supports Python 2.7

### ISSUE THREAD

**Issue by becurrie** [rheinwerk-verlag/postgresql-anonymizer#35]
parmap release `1.5.3` dropped support for older versions of Python.

Relevant changelog entry:

> parmap (1.5.3)
> 
>   * Drop support for unsupported python versions
>   * Add support for python 3.10
>   * Use tqdm.auto to have nice progress bars on jupyter notebooks (#26)
>   * Add dummy _number_left for parallel async (#23)

Downgrading my parmap to 1.5.2 does fix the issue on older versions of Python.

**Comment by hkage** [comment]
Thanks for reporting the issue. I will pin the parmap version for Python 2.7 to that version.

**Comment by hkage** [comment]
I will release this fix with the next, upcoming version 0.7.0. Thanks again for reporting.
